# Generated by Django 2.2.10 on 2020-02-16 02:31

from django.db import migrations, models
import django.db.models.deletion
import helpers.date_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('prints', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(default='Creality Ender 3', max_length=255)),
                ('max_x', models.CharField(default='220', max_length=255)),
                ('max_y', models.CharField(default='220', max_length=255)),
                ('max_z', models.CharField(default='250', max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('changed', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('created', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.Address')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prints.Material')),
            ],
        ),
    ]
