# Generated by Django 2.2.9 on 2020-02-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
