# Generated by Django 2.2.9 on 2020-02-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_auto_20200213_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='max_x',
            field=models.CharField(default='220', max_length=255),
        ),
        migrations.AddField(
            model_name='printer',
            name='max_y',
            field=models.CharField(default='220', max_length=255),
        ),
        migrations.AddField(
            model_name='printer',
            name='max_z',
            field=models.CharField(default='250', max_length=255),
        ),
        migrations.AddField(
            model_name='printer',
            name='model',
            field=models.CharField(default='Creality Ender 3', max_length=255),
        ),
    ]
