
languaje: python

before_script:
  - sudo /etc/init.d/postgresql stop

sudo: required

services:
  - docker

install:
  - docker-compose build

script:
  - docker-compose run -e COVERALLS_REPO_TOKEN="$repo_token" django bash -c "pytest --cov-report=xml && coveralls"