version: "3"

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
    django:
        build: .
        stdin_open: true
        tty: true
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./src:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - AMAZON_ACCESS_KEY_ID=${AMAZON_ACCESS_KEY_ID}
            - AMAZON_ACCESS_SECRET_KEY=${AMAZON_ACCESS_SECRET_KEY}
            - IMAGES_BUCKET_NAME=${IMAGES_BUCKET_NAME}
            - MODELS_BUCKET_NAME=${MODELS_BUCKET_NAME}
