FROM python:3.7.2

ENV PYTHONUNBUFFERED 1
ENV AMAZON_ACCESS_KEY_ID $AMAZON_ACCESS_KEY_ID
ENV AMAZON_ACCESS_SECRET_KEY $AMAZON_ACCESS_SECRET_KEY
ENV IMAGES_BUCKET_NAME $IMAGES_BUCKET_NAME
ENV MODELS_BUCKET_NAME $MODELS_BUCKET_NAME

RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
COPY ./src /app
