FROM python:3.7

ENV PYTHONUNBUFFERED 1
ENV AMAZON_ACCESS_KEY_ID $AMAZON_ACCESS_KEY_ID
ENV AMAZON_ACCESS_SECRET_KEY $AMAZON_ACCESS_SECRET_KEY
ENV IMAGES_BUCKET_NAME $IMAGES_BUCKET_NAME
ENV MODELS_BUCKET_NAME $MODELS_BUCKET_NAME

RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt
RUN apt-get update
RUN apt-get install blender -y
COPY ./src /app
