# Generated by Django 2.2.9 on 2020-01-14 23:09

from django.db import migrations, models
import helpers.date_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('changed', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('created', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
            ],
        ),
    ]
