# Generated by Django 2.2.9 on 2020-01-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
