# Generated by Django 2.2.9 on 2020-01-22 00:37

from django.db import migrations, models
import django.db.models.deletion
import helpers.date_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('changed', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('created', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
