# Generated by Django 2.2.2 on 2019-09-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('mercado_pago_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField()),
                ('changed', models.DateTimeField()),
            ],
        ),
    ]
