# Generated by Django 2.2.10 on 2020-02-16 02:35

from django.db import migrations, models
import django.db.models.deletion
import helpers.date_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
        ('models', '0001_initial'),
        ('addresses', '0001_initial'),
        ('users', '0001_initial'),
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('price', models.CharField(max_length=255)),
                ('scale', models.CharField(max_length=255)),
                ('changed', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('created', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Address')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prints.Material')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Model')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printers.Printer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User')),
            ],
        ),
    ]
