# Generated by Django 2.2.9 on 2020-01-22 00:37

from django.db import migrations, models
import django.db.models.deletion
import helpers.date_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_medias', '0001_initial'),
        ('model_medias', '__first__'),
        ('users', '0002_user_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('changed', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('created', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('father_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('volume', models.CharField(max_length=255)),
                ('max_x', models.CharField(max_length=255)),
                ('max_z', models.CharField(max_length=255)),
                ('max_y', models.CharField(max_length=255)),
                ('privacy', models.IntegerField()),
                ('printed_quantity', models.IntegerField(default=0)),
                ('changed', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('created', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Category')),
                ('image_media', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_model', to='image_medias.ImageMedia')),
                ('model_media', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_media', to='model_medias.ModelMedia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
