# Generated by Django 2.2.8 on 2019-12-18 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_media',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='model_media', to='model_medias.ModelMedia'),
        ),
        migrations.AlterField(
            model_name='model',
            name='volume',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
