# Generated by Django 2.2.6 on 2019-10-24 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_media',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='model_media', to='model_medias.ModelMedia'),
        ),
    ]
