# Generated by Django 2.2.5 on 2019-09-19 02:14

from django.db import migrations, models
import django.db.models.deletion
import helpers.date_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190911_0142'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('model_url', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('privacy', models.IntegerField()),
                ('changed', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('created', models.DateTimeField(default=helpers.date_helpers.get_current_utc_datetime)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Category')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
