# Generated by Django 2.2.8 on 2019-12-18 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20191218_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='image_media',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_model', to='image_medias.ImageMedia'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_media',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_media', to='model_medias.ModelMedia'),
        ),
    ]
