# Generated by Django 2.2.5 on 2019-09-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='user_id',
            new_name='user',
        ),
    ]
