# Generated by Django 2.2.9 on 2020-01-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20191218_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='printed_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
