# Generated by Django 2.2.5 on 2019-09-19 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
        ('models', '0003_auto_20190919_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='model',
            name='model_url',
        ),
        migrations.AddField(
            model_name='model',
            name='media_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image_model', to='medias.Media'),
        ),
        migrations.AddField(
            model_name='model',
            name='media_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='model_model', to='medias.Media'),
        ),
    ]
