"""
Django settings for vortex project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ft7&vef-6*vsb!i)58gw=$ubu!!lf@rm!&!0wn7&5kabcz=1_x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'infra',
    'users',
    'models',
    'image_medias',
    'model_medias',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
]

ROOT_URLCONF = 'vortex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vortex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'db',
        'PORT': 5432,
    }
}

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


# Amazon s3

AMAZON_ACCESS_KEY_ID = os.getenv('AMAZON_ACCESS_KEY_ID')
AMAZON_ACCESS_SECRET_KEY = os.getenv('AMAZON_ACCESS_SECRET_KEY')
IMAGES_BUCKET_NAME = os.getenv('IMAGES_BUCKET_NAME')
MODELS_BUCKET_NAME = os.getenv('MODELS_BUCKET_NAME')
BASE_AMAZON_URL = "https://{BUCKET_NAME}.s3.us-east-2.amazonaws.com/{RESOURCE_NAME}"
