# Overwrite configurations
from .settings import *

AMAZON_ACCESS_KEY_ID = 'ACCESS_KEY'
AMAZON_ACCESS_SECRET_KEY = 'SECRET_KEY'
IMAGES_BUCKET_NAME = 'TESTING_IMAGES_BUCKET'
MODELS_BUCKET_NAME = 'TESTING_MODELS_BUCKET'
